"""What a vouched tree leaves in the workshop (ADR-0013).

A Setup carries a capability. A skill belongs in one; the tests that prove the
skill works do not, and neither does the cache the test runner left behind.
That is not a judgement about worth - they are worth keeping, and keeping them
is a backup's job rather than a Snapshot's.

Who this may be asked about is the whole safety property, and it is not asked
here. Only a VOUCHED declaration - a directory an Adapter named on the user's
behalf - is narrowed by this list. A handpicked path is the user's own word
about their own machine (ADR-0008), and a `carry` entry pointing at a directory
called `tests` is carried as a directory called `tests`. The engine asks the
declaration before it asks this module; nothing here can tell the two apart.

Three things this list is NOT.

It is not a gate. Nothing about credentials may depend on it: the scanner still
runs over everything that survives it, and a prune list that ever became load-
bearing for secrecy would be a list somebody has to keep complete, which is
exactly what ADR-0010 warns a list cannot be. The state gate is the same rule
seen from the other side - `capture.state_reads` runs over everything DECLARED,
this list included, so a second name for the master key parked in a test tree
refuses the capture even though the tree would not have been carried. That is
wider than it needs to be, and deliberately: a gate that consulted this list
would be a gate whose coverage depended on a name being on it.

It is not a vendor table. Every entry is about the shape of software - a test
tree, a type checker's cache - rather than about any agent, so a vendor
reorganising their directory does not date it. ADR-0010 is explicit about what
a maintained-by-reading list costs, and this one is kept small to be worth it.

It is not a judgement about size. A dependency tree - `node_modules`, a
virtualenv, a vendored `dist` - is the biggest thing in most repositories and
is deliberately absent: those belong to USING the thing, and a capability that
needs one and does not find it is a capability that did not survive the move.
The test is what a directory is for, not what it weighs.

So it fails in the safe direction. An unrecognised development directory is
carried, which is the status quo; nothing needed is ever dropped for want of a
name on this list.
"""

from __future__ import annotations

import pathlib

DEVELOPMENT_DIRS = frozenset({
    # A test suite and its fixtures. The observed case, and the reason this
    # module exists: a third of one machine's carried skill bytes.
    "tests",
    "test",
    "__tests__",
    # Caches and run output. Regenerated by the tool that made them, on the
    # machine that runs it, and meaningless on any other.
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    "htmlcov",
})

WHAT = "development artifact"
WHY = ("a Setup carries a capability, not what built it - the skill moves, "
       "its test suite stays (ADR-0013)")


def workshop_prefix(rel: pathlib.PurePath):
    """The top-most Development artifact directory on the way to `rel`, or
    None when nothing on that path is one.

    `rel` is a file's path relative to the root of the tree being carried, and
    the answer is a prefix of it - a DIRECTORY, named once, however many files
    stand under it. A tests tree with its own fixtures and its own caches is
    one sentence the user can act on rather than a wall they scroll past, and
    the top-most hit is the one that names the thing they would actually
    delete.

    Only the directories are asked, never the last component: a skill whose
    entire content is a file named `tests` is a skill with a file in it, and
    dropping that file would drop the capability this list exists to protect.

    Matched case-folded, because macOS folds case and Linux does not - so a
    directory called `Tests` is the same directory as `tests` on the machine
    that made it and a different one on the machine that receives it. What it
    IS does not depend on which of those the user is standing on.
    """
    parts = rel.parts[:-1]
    for index, part in enumerate(parts):
        if part.casefold() in DEVELOPMENT_DIRS:
            return type(rel)(*parts[:index + 1])
    return None
