"""Generate the restore notes that ship inside a captured Setup.

Ordering is the point of this file. Installing an agent after writing its
config lets first launch clobber what you just restored, and restoring curated
memory before `carryon pull` lets the verbatim copy win. Both are easy to get
wrong and annoying to undo, so the Setup carries the order with it.

Every string that reaches the document goes through `printable` first. What is
rendered here is not carryon's own prose: an item's src and dst come from an
adapter, an agent's name and an exclusion note come from a stored MANIFEST the
Destination authored (ADR-0009), and an external link's target comes from
readlink - which on macOS may hold bytes that are no encoding at all, since
APFS polices filenames and not link targets. The three callers all end in
Path.write_text, which encodes strictly, so one such string ended `carryon
push` and `carryon capture` with a UnicodeEncodeError. The guard belongs here
because this is the one function all three go through, and the previous fix
put it on the stored document only - one of the two doors.
"""

from __future__ import annotations

from .destinations.base import printable


def _carried_skills(manifest: dict) -> list:
    out = []
    for agent in manifest["agents"].values():
        for item in agent["items"]:
            out.extend(printable(name) for name in item.get("carried", []))
    return out


def _copy_lines(manifest: dict) -> list:
    lines = []
    for agent in manifest["agents"].values():
        for item in agent["items"]:
            if item["kind"] in ("file", "json-strip") and "skill-lock" not in item["dst"]:
                dst, src = printable(item["dst"]), printable(item["src"])
                lines.append(f"    cp {dst:<44} ~/{src}")
    return lines


def build_restore(manifest: dict) -> str:
    names = [printable(a["name"]) for a in manifest["agents"].values()]
    out = [
        "# Restore on the new machine",
        "",
        f"Generated by carryon {printable(manifest['version'])} on "
        f"{printable(manifest['captured_at'])}.",
        f"Agents in this Setup: {', '.join(names) if names else 'none'}.",
        "",
        "## 1. Install the agents and log in, before copying anything",
        "",
        "First launch writes an agent's own defaults and will overwrite config you",
        "restored early. No credentials are in this Setup - that is deliberate,",
        "they are machine-bound and you log in again.",
        "",
        "## 2. Launch each agent once, then quit",
        "",
        "This creates the directories the current version expects, rather than you",
        "recreating an older layout by hand.",
        "",
        "## 3. Re-resolve skills from upstream",
        "",
        "`agents/.skill-lock.json` records the upstream repo and hash per skill.",
        "Re-install from it rather than copying bytes, so you get current versions",
        "instead of importing a stale snapshot.",
        "",
    ]

    carried = _carried_skills(manifest)
    if carried:
        out += [
            "Then copy the skills with NO upstream. These exist only in this Setup;",
            "if they are not restored, they are gone:",
            "",
        ]
        out += [f"    cp -R claude/skills/{name} ~/.claude/skills/" for name in carried]
        out.append("")

    external = {}
    for agent in manifest["agents"].values():
        for item in agent["items"]:
            external.update(item.get("external", {}))
    if external:
        out += [
            "Some skills are symlinks managed by something else - a dotfiles",
            "repo, most likely. They are not in this Setup and the skills",
            "installer will not restore them. Whatever owns these must run too:",
            "",
        ]
        out += [f"    {printable(name)}  <- {printable(target)}"
                for name, target in sorted(external.items())]
        out += [
            "",
            "A target under `~` was that path on the machine this Setup came",
            "from: what travels to a Destination names no particular home",
            "(ADR-0006). Where your dotfiles put it here is their business,",
            "not carryon's - it never writes through one of these links.",
            "",
            "A target shown as withheld pointed somewhere `~` cannot express -",
            "another volume, a team share, a spelling of the home that differs",
            "only by case. The name is still yours to re-create; the path it",
            "had on that machine is not something an Archive gets to carry.",
            "",
        ]

    out += ["## 4. Config and knowledge", ""] + _copy_lines(manifest) + [""]

    out += [
        "## 5. History - last, with `carryon pull`",
        "",
        "This Setup contains no Transcripts. The History travels in the Archive,",
        "encrypted, and pull lays it down against this machine's home:",
        "",
        "    carryon pull            # dry run: shows the plan",
        "    carryon pull --apply",
        "",
        "Two things to know first:",
        "",
        "- A History is unredacted by nature: push does NOT redact. A Transcript",
        "  records everything ever printed to a terminal, credentials included;",
        "  carryon reports how many look like that, then encrypts and carries",
        "  them anyway. The Archive is only as safe as your recovery key.",
        "- Pull unions a History: it never deletes a local Session, and a",
        "  divergent copy is kept under ~/.carryon/conflicts/ instead of",
        "  overwriting yours.",
        "- It writes per-project memory. If you also restore curated memory from a",
        "  dotfiles repo, run `carryon pull` FIRST and dotfiles SECOND, so the",
        "  curated version wins.",
        "",
        "## 6. Re-install rather than migrate",
        "",
    ]
    for agent in manifest["agents"].values():
        for ex in agent["excluded"]:
            out.append(f"- `{printable(ex['path'])}` - "
                       f"{printable(ex['what'])}: {printable(ex['why'])}")

    out += [
        "",
        "## 7. Check before deleting anything on the old machine",
        "",
        "Launch each agent and confirm its skills, settings and instructions are",
        "present. `MANIFEST.json` lists exactly what was captured.",
        "",
    ]
    return "\n".join(out)
