"""Generate the restore notes that ship inside the bundle.

Ordering is the point of this file. Installing an agent after writing its
config lets first launch clobber what you just restored, and restoring curated
memory before entangle lets the verbatim copy win. Both are easy to get wrong
and annoying to undo, so the bundle carries the order with it.
"""

from __future__ import annotations

ENTANGLE = "https://github.com/gowtham-sai-yadav/claude-teleport"


def _carried_skills(manifest: dict) -> list:
    out = []
    for agent in manifest["agents"].values():
        for item in agent["items"]:
            out.extend(item.get("carried", []))
    return out


def _copy_lines(manifest: dict) -> list:
    lines = []
    for agent in manifest["agents"].values():
        for item in agent["items"]:
            if item["kind"] in ("file", "json-strip") and "skill-lock" not in item["dst"]:
                lines.append(f"    cp {item['dst']:<44} ~/{item['src']}")
    return lines


def build_restore(manifest: dict) -> str:
    names = [a["name"] for a in manifest["agents"].values()]
    out = [
        "# Restore on the new machine",
        "",
        f"Generated by carryon {manifest['version']} on {manifest['captured_at']}.",
        f"Agents in this bundle: {', '.join(names) if names else 'none'}.",
        "",
        "## 1. Install the agents and log in, before copying anything",
        "",
        "First launch writes an agent's own defaults and will overwrite config you",
        "restored early. No credentials are in this bundle - that is deliberate,",
        "they are machine-bound and you log in again.",
        "",
        "## 2. Launch each agent once, then quit",
        "",
        "This creates the directories the current version expects, rather than you",
        "recreating an older layout by hand.",
        "",
        "## 3. Re-resolve skills from upstream",
        "",
        "`agents/.skill-lock.json` records the upstream repo and hash per skill.",
        "Re-install from it rather than copying bytes, so you get current versions",
        "instead of importing a stale snapshot.",
        "",
    ]

    carried = _carried_skills(manifest)
    if carried:
        out += [
            "Then copy the skills with NO upstream. These exist only in this bundle;",
            "if they are not restored, they are gone:",
            "",
        ]
        out += [f"    cp -R claude/skills/{name} ~/.claude/skills/" for name in carried]
        out.append("")

    out += ["## 4. Config and knowledge", ""] + _copy_lines(manifest) + [""]

    out += [
        "## 5. History - last, and with a different tool",
        "",
        "This bundle contains no transcripts. Use entangle:",
        "",
        f"    # {ENTANGLE}",
        "    entangle export --out ~/agent-sessions.tgz     # old machine",
        "    entangle import ~/agent-sessions.tgz --dry-run  # new machine",
        "    entangle import ~/agent-sessions.tgz",
        "",
        "Two things to know first:",
        "",
        "- `entangle export` does NOT redact. It copies transcripts verbatim, and a",
        "  transcript records everything ever printed to the terminal, including any",
        "  credential a tool happened to echo. Treat the .tgz as a secret: move it by",
        "  USB or `entangle send`, never cloud storage or git, and delete it after.",
        "- It writes per-project memory. If you also restore curated memory from a",
        "  dotfiles repo, run entangle FIRST and dotfiles SECOND, so the curated",
        "  version wins.",
        "",
        "## 6. Re-install rather than migrate",
        "",
    ]
    for agent in manifest["agents"].values():
        for ex in agent["excluded"]:
            out.append(f"- `{ex['path']}` - {ex['what']}: {ex['why']}")

    out += [
        "",
        "## 7. Check before deleting anything on the old machine",
        "",
        "Launch each agent and confirm its skills, settings and instructions are",
        "present. `MANIFEST.json` lists exactly what was captured.",
        "",
    ]
    return "\n".join(out)
